### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by MostHated** [marcolink/StringTable#6]
Hey there, 
    Since it's been nearly a year since someone mentioned that the Nuget package doesn't work (I just noticed it myself, which was what brought me to the issues), would you be against making the license MIT? I would not mind using it, but can't add a reference to the package because it doesn't work and I have never been comfortable including actual code unless it's MIT licensed.

Thanks,
-MH

**Comment by marcolink** [comment]
Hi @MostHated,
I wouldn't mind doing so, I just wonder what particular issue you see with the current license?

**Comment by MostHated** [comment]
It's definitely not that there is anything wrong with the choice of license. It's just my own dumb personal anxiety/paranoia that I am forgetting some term of the license, or that I didn't do some minute detail that might come back to bite me one day. (even though I know that won't actually happen... but what if it does, just to me? Anxiety is terrible man, I tell you.)

I am not well versed in license terms and conditions, and after some time, I just found I feel much more at ease integrating a package that is MIT licensed since it is so simple and straight forward, and I don't have to worry about if I am right or wrong in my knowledge of licenses, or that I am doing something incorrectly, that might (even though it won't....) cause issue.

Now that I write it out and read it back to myself, I see how ridiculous it sounds, lol. My bad, nevermind about the whole thing.
